#!/bin/sh
#
# PearlPBX init script 
### BEGIN INIT INFO
# Provides:          PearlPBX
# Required-Start:    $local_fs $remote_fs $network $syslog $asterisk
# Required-Stop:     $local_fs $remote_fs $network $syslog $asterisk
# Should-Start:      postgresql asterisk 
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PearlPBX - WebGUI for asterisk written by Alex Radetsky ( www.pearlpbx.com ) 
### END INIT INFO

. /etc/rc.d/init.d/functions

PATH=/opt/NetSDS/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="PearlPBX"
DESC="PearlPBX WebGUI"
UMASK=007 # by default

# by default: use real-time priority
PARAMS=""
CHDIR_PARM=""

mkdir -p /var/run/NetSDS 

first_run_pearlpbx() {

ln -sf /etc/NetSDS /etc/PearlPBX
chkconfig pearlpbx-parsequeuelogd off
chkconfig pearlpbx-hangupd off
chkconfig PearlPBX on 
chkconfig asterisk off
chkconfig postgresql off
chkconfig httpd on
chkconfig monit on
/etc/init.d/postgresql initdb
/etc/init.d/postgresql start
psql -U postgres -f /etc/NetSDS/sql/create_user_asterisk.sql
psql -U postgres -f /etc/NetSDS/sql/asterisk.sql
psql -U postgres -f /etc/NetSDS/sql/local_route.sql
psql -U asterisk -f /etc/NetSDS/sql/directions_list.sql
psql -U asterisk -f /etc/NetSDS/sql/directions.sql
psql -U asterisk -f /etc/NetSDS/sql/sip_conf.sql
psql -U asterisk -f /etc/NetSDS/sql/extensions_conf.sql
psql -U asterisk -f /etc/NetSDS/sql/route.sql
psql -U asterisk -f /etc/NetSDS/sql/cal.sql
psql -U asterisk -f /etc/NetSDS/sql/ivr.sql
mv -f /etc/PearlPBX/asterisk/* /etc/asterisk/
/usr/sbin/PearlPBX-gui-passwd.pl admin admin
/usr/bin/ulines.pl
mkdir /var/www/pearlpbx/files
chown apache:apache /var/www/pearlpbx/files
mkdir /usr/share/asterisk/sounds/ru/pearlpbx
chown apache:apache /usr/share/asterisk/sounds/ru/pearlpbx
/etc/init.d/postgresql stop
echo "Installed" >/etc/sysconfig/PearlPBX

}


start() {
		echo -n "Starting $DESC: $NAME"
		/etc/init.d/postgresql start 
		/etc/init.d/asterisk start 
		/etc/init.d/pearlpbx-hangupd start 
		/etc/init.d/pearlpbx-parsequeuelogd start 
	  echo "."
}

stop() { 
	echo -n "Stopping $DESC: $NAME"
	/etc/init.d/pearlpbx-parsequeuelogd stop 
	/etc/init.d/pearlpbx-hangupd stop 
	/etc/init.d/asterisk stop 
	/etc/init.d/postgresql stop 
	echo "."
}

restart() { 
	stop
	start
}

case "$1" in
	start)
	if [ -f /etc/sysconfig/PearlPBX ] 
	then
		start
	else 
		first_run_pearlpbx
		start
	fi
;; 
  stop)
	stop
;;
	restart)
	restart
;;

  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
