#!/bin/sh
#
# PearlPBX init script 
### BEGIN INIT INFO
# Provides:          PearlPBX
# Required-Start:    $local_fs $remote_fs $network $syslog $asterisk
# Required-Stop:     $local_fs $remote_fs $network $syslog $asterisk
# Should-Start:      postgresql asterisk 
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PearlPBX - WebGUI for asterisk written by Alex Radetsky ( www.pearlpbx.com ) 
### END INIT INFO

. /etc/rc.d/init.d/functions

PATH=/opt/NetSDS/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="PearlPBX"
DESC="PearlPBX WebGUI"
UMASK=007 # by default

# by default: use real-time priority
PARAMS=""
CHDIR_PARM=""

mkdir -p /var/run/NetSDS 

first_run_pearlpbx() {

ln -sf /etc/NetSDS /etc/PearlPBX
systemctl disable pearlpbx-parsequeuelogd.service 
systemctl disable pearlpbx-hangupd.service
systemctl enable PearlPBX.service
systemctl disable asterisk.service
systemctl disable postgresql.service 
systemctl disable httpd.service  
systemctl enable monit.service  
/usr/bin/postgresql-setup initdb
cp /var/lib/pgsql/data/pg_hba.conf /tmp/pg_hba.conf 
cat /tmp/pg_hba.conf | sed 's/ident$/trust/' >/var/lib/pgsql/data/pg_hba.conf
cp /var/lib/pgsql/data/pg_hba.conf /tmp/pg_hba.conf 
cat /tmp/pg_hba.conf | sed 's/peer$/trust/' >/var/lib/pgsql/data/pg_hba.conf
systemctl start postgresql.service
psql -U postgres -f /etc/NetSDS/sql/create_user_asterisk.sql
psql -U postgres -f /etc/NetSDS/sql/asterisk.sql
psql -U asterisk -f /etc/NetSDS/sql/callback.sql
psql -U asterisk -f /etc/NetSDS/sql/directions_list.sql
psql -U asterisk -f /etc/NetSDS/sql/directions.sql
psql -U asterisk -f /etc/NetSDS/sql/sip_conf.sql
psql -U asterisk -f /etc/NetSDS/sql/extensions_conf.sql
psql -U asterisk -f /etc/NetSDS/sql/route.sql
psql -U asterisk -f /etc/NetSDS/sql/local_route.sql
psql -U asterisk -f /etc/NetSDS/sql/cal.sql
psql -U asterisk -f /etc/NetSDS/sql/ivr.sql
mv -f /etc/PearlPBX/asterisk/* /etc/asterisk/
/usr/sbin/PearlPBX-gui-passwd.pl admin admin
/usr/bin/ulines.pl
mkdir /var/www/pearlpbx/files
chown apache:apache /var/www/pearlpbx/files
mkdir /usr/share/asterisk/sounds/ru/pearlpbx
chown apache:apache /usr/share/asterisk/sounds/ru/pearlpbx
systemctl stop postgresql 

firewall-cmd --permanent  --add-service=http
firewall-cmd --permanent  --add-port=5060/udp 
firewall-cmd --permanent  --add-port=5060/tcp 
firewall-cmd --permanent  --add-port=5061/tcp 
firewall-cmd --reload 

echo "Installed" >/etc/sysconfig/PearlPBX

}


start() {
		echo "Starting $DESC: $NAME"
		systemctl start postgresql
		sleep 3
		systemctl start asterisk 
		systemctl start pearlpbx-hangupd 
		systemctl start pearlpbx-parsequeuelogd 
		/usr/sbin/asterisk -rx "queue show"
		systemctl start httpd 
		echo "."
}

stop() { 
	echo -n "Stopping $DESC: $NAME"
	/etc/init.d/httpd stop 
	/etc/init.d/pearlpbx-parsequeuelogd stop 
	/etc/init.d/pearlpbx-hangupd stop 
	/etc/init.d/asterisk stop 
	/etc/init.d/postgresql stop 
	echo "."
}

restart() { 
	stop
	start
}

case "$1" in
	start)
	if [ -f /etc/sysconfig/PearlPBX ] 
	then
		start
	else 
		first_run_pearlpbx
		start
	fi
;; 
  stop)
	stop
;;
	restart)
	restart
;;

  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
